[package]
authors = ["Xuanwo <github@xuanwo.io>"]
categories = ["command-line-utilities"]
description = "Layered configuration system built upon serde"
documentation = "https://docs.rs/serfig"
edition = "2021"
license = "Apache-2.0"
name = "serfig"
version = "0.0.0"

[dependencies]
serde="1.0.136"
serde-bridge = { path = "../serde-bridge" }
anyhow = "1.0.56"
envy = "0.4.1"
indexmap = "1.8.1"
toml = "0.5.9"

[dev-dependencies]
serde = {version="1.0.136", features=["derive"]}
temp-env = "0.2.0"
