[package]
authors = ["Xuanwo <github@xuanwo.io>"]
categories = ["command-line-utilities"]
description = "Load config via serde in layered way"
documentation = "https://docs.rs/serfig"
edition = "2021"
license = "Apache-2.0"
name = "serfig"
version = "0.0.0"

[dependencies]
